"""Pass 1 runtime trace.

Ingests data/fixtures/tahari_r0_preupload_template_2026_05_14.xlsx through
the actual parse + form-state + evaluate path, and dumps:

  1. raw parsed style dict
  2. style_to_form_state(...) output (the keys the engine view sees)
  3. evaluate_form(...) verdict per field
  4. divergence report: which fields had data in state but verdict reports missing

Writes a markdown report to docs/pass1_runtime_trace.md.

Run: python scripts/pass1_runtime_trace.py
"""
from __future__ import annotations

import json
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIXTURE = ROOT / "data" / "fixtures" / "tahari_r0_preupload_template_2026_05_14.xlsx"
REPORT  = ROOT / "docs" / "pass1_runtime_trace.md"

sys.path.insert(0, str(ROOT))

from nis_engine.preupload_importer import parse_preupload, style_to_form_state  # noqa: E402
from nis_engine import nis_rule_engine as _nis_engine  # noqa: E402
from nis_engine import pt_defaults as _pt_defaults  # noqa: E402

# Point the engine at the rule bundle dir before calling evaluate_form
_NIS_RULES_DIR = ROOT / "nis_rules"
if _NIS_RULES_DIR.exists():
    _nis_engine.set_bundle_dir(str(_NIS_RULES_DIR))


def _dump(state: dict) -> str:
    lines = []
    for k in sorted(state.keys()):
        v = state[k]
        v_repr = v if isinstance(v, str) and len(v) < 80 else (str(v)[:80] + "…")
        lines.append(f"  {k:48s} = {v_repr!r}")
    return "\n".join(lines)


def main() -> int:
    if not FIXTURE.exists():
        print(f"missing fixture: {FIXTURE}", file=sys.stderr)
        return 1

    parsed = parse_preupload(str(FIXTURE))
    brand = parsed.get("brand") or ""
    styles = parsed.get("styles", {})

    print(f"brand: {brand!r}, styles parsed: {len(styles)}")
    if not styles:
        print("no styles parsed — aborting", file=sys.stderr)
        return 1

    # Filter out the template's REQUIRED/OPTIONAL labels (row 2) and column
    # descriptions (row 3). Real STYLE# values are 9-digit numbers; labels and
    # descriptions are alphabetic or sentence text.
    SENTINELS = {"REQUIRED", "OPTIONAL", "IMPORTANT", ""}
    def _is_real_style(sid: str) -> bool:
        s = (sid or "").strip()
        if s.upper() in SENTINELS:
            return False
        # Real style numbers in TLG templates are alphanumeric, no spaces, length 6-12
        if " " in s or len(s) > 14 or len(s) < 5:
            return False
        return True

    real_styles = {sid: s for sid, s in styles.items() if _is_real_style(sid)}
    print(f"after filtering sentinels: {len(real_styles)} real styles")

    # Prefer a TAHARI row with a populated fabric AND closure (typical Tahari puffer)
    sample_id = None
    sample = None
    for sid, s in real_styles.items():
        tlg = (s.get("tlgdiv") or "").upper()
        if "TAHARI" in tlg and s.get("fabric") and s.get("closure"):
            sample_id, sample = sid, s
            break
    if sample_id is None:
        # fall back to first real style
        sample_id, sample = next(iter(real_styles.items()))

    # Re-derive brand from the actual sample row's TLGDIV
    tlg = (sample.get("tlgdiv") or "").upper()
    if "TAHARI" in tlg:
        brand = "Tahari"
    elif "VOLCOM" in tlg:
        brand = "Volcom"
    print(f"sample style_id: {sample_id}, name: {sample.get('name')!r}, brand resolved: {brand!r}")

    state = style_to_form_state(sample, brand)
    evaluation = _nis_engine.evaluate_form(
        "COAT", state,
        apply_apparel_defaults=True,
        brand=brand,
        sub_class=sample.get("sub_class") or "",
    )

    eval_fields = evaluation.get("fields", {})

    # Build divergence report: state has value, verdict reports missing
    diverged = []
    for ek, ef in sorted(eval_fields.items()):
        verdict = ef.get("verdict")
        label = ef.get("label")
        # Try to find the matching state key. The eval fields key is the canonical
        # field_key (e.g. "closure"); state writes "closure#1.type#1.value".
        candidates = [k for k in state.keys() if k.startswith(ek + "#") or k == ek]
        state_val = None
        for c in candidates:
            state_val = state.get(c)
            if state_val not in (None, "", " "):
                break
        if verdict == "required_missing" and state_val:
            diverged.append({
                "field": ek,
                "label": label,
                "state_keys": candidates,
                "state_value": state_val,
                "verdict": verdict,
                "base_requirement": ef.get("base_requirement"),
            })

    # Write report
    lines = []
    lines.append("# Pass 1 runtime trace — Tahari R0 fixture")
    lines.append("")
    lines.append("> Source: `scripts/pass1_runtime_trace.py`. Generated by feeding")
    lines.append("> `data/fixtures/tahari_r0_preupload_template_2026_05_14.xlsx` through")
    lines.append("> `parse_preupload → style_to_form_state → evaluate_form`.")
    lines.append("")
    lines.append(f"- Brand parsed: `{brand}`")
    lines.append(f"- Styles parsed: {len(styles)}")
    lines.append(f"- Sample style_id: `{sample_id}`")
    lines.append(f"- Sample name: `{sample.get('name')}`")
    lines.append(f"- Sample sub_class: `{sample.get('sub_class')}`")
    lines.append("")
    lines.append("## Raw parsed style (selected fields)")
    lines.append("")
    lines.append("```")
    for k in ("brand", "name", "sub_class", "department", "fabric", "closure",
              "sleeve_type", "sleeve_length", "neck", "fit", "length", "coo",
              "care", "colors", "sizes", "model", "style"):
        if k in sample:
            v = sample[k]
            lines.append(f"  {k:18s} = {v!r}")
    lines.append("```")
    lines.append("")
    lines.append("## style_to_form_state output (full)")
    lines.append("")
    lines.append("```")
    lines.append(_dump(state))
    lines.append("```")
    lines.append("")
    lines.append(f"## Evaluation summary")
    lines.append("")
    summary = evaluation.get("summary", {})
    lines.append("```")
    lines.append(json.dumps(summary, indent=2, default=str))
    lines.append("```")
    lines.append("")

    # Item 5 divergence
    lines.append("## Divergence — fields where state has a value but verdict reports `required_missing`")
    lines.append("")
    if not diverged:
        lines.append("_None._ The verdict and the state agree for this sample row.")
    else:
        lines.append(f"**{len(diverged)} fields diverged.** This is Item 5 (false blockers) — confirmed.")
        lines.append("")
        for d in diverged:
            lines.append(f"### `{d['field']}` ({d['label']})")
            lines.append(f"- verdict: `{d['verdict']}` ({d['base_requirement']})")
            lines.append(f"- state keys checked: `{d['state_keys']}`")
            v_repr = d['state_value'] if len(str(d['state_value'])) < 80 else (str(d['state_value'])[:80] + "…")
            lines.append(f"- state value: `{v_repr}`")
            lines.append("")

    # Item 9 — Closure Type key namespace check
    lines.append("## Item 9 — Closure Type key namespace")
    lines.append("")
    closure_state_keys = [k for k in state.keys() if "closure" in k]
    closure_eval_keys = [k for k in eval_fields.keys() if "closure" in k.lower()]
    lines.append("```")
    lines.append(f"  state keys mentioning 'closure':       {closure_state_keys}")
    lines.append(f"  evaluation keys mentioning 'closure':  {closure_eval_keys}")
    lines.append("```")
    lines.append("")

    # Item 11 — Material vs Fabric Type — what's in each
    lines.append("## Item 11 — Material vs Fabric Type values")
    lines.append("")
    lines.append("```")
    for k in sorted(state.keys()):
        if "material" in k or "fabric" in k:
            lines.append(f"  {k:48s} = {state[k]!r}")
    lines.append("```")
    lines.append("")
    lines.append("Symptom: both fields receive the same percentage string. Material slot should hold")
    lines.append("just the material *names* (e.g. `Polyester`), while Fabric Type should hold the")
    lines.append("composition string (`100% Polyester`).")
    lines.append("")

    # Item 13 — Sleeve Length presence
    lines.append("## Item 13 — Sleeve Length presence in writer")
    lines.append("")
    sleeve_state_keys = [k for k in state.keys() if "sleeve" in k]
    lines.append("```")
    lines.append(f"  state keys mentioning 'sleeve':  {sleeve_state_keys}")
    lines.append("```")
    if "sleeve_length" not in str(sleeve_state_keys):
        lines.append("")
        lines.append("`sleeve_length` is **not** present in state. Confirmed: writer never maps it.")
    lines.append("")

    # Item 8 — Department + Target Gender
    lines.append("## Item 8 — Department + Target Gender values in state")
    lines.append("")
    lines.append("```")
    for k in sorted(state.keys()):
        if "department" in k or "target_gender" in k or "gender" in k:
            lines.append(f"  {k:48s} = {state[k]!r}")
    lines.append("```")
    lines.append("")

    REPORT.write_text("\n".join(lines))
    print(f"\nWrote {REPORT}")
    print(f"Diverged fields (Item 5 confirmed): {len(diverged)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
